// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/views/pages/About.vue')['default']
    AddItem: typeof import('./src/views/modules/addItem.vue')['default']
    AddRestaurant: typeof import('./src/views/modules/AddRestaurant.vue')['default']
    Business: typeof import('./src/views/pages/Business.vue')['default']
    BusinessAbout: typeof import('./src/views/modules/BusinessAbout.vue')['default']
    BusinessRestaurants: typeof import('./src/views/modules/businessRestaurants.vue')['default']
    Cart: typeof import('./src/views/modules/Cart.vue')['default']
    Carts: typeof import('./src/views/pages/Carts.vue')['default']
    CategoryFilter: typeof import('./src/components/CategoryFilter.vue')['default']
    CreateItem: typeof import('./src/components/CreateItem.vue')['default']
    CreateItemView: typeof import('./src/views/CreateItemView.vue')['default']
    Favorites: typeof import('./src/views/modules/Favorites.vue')['default']
    Home: typeof import('./src/views/pages/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Item: typeof import('./src/views/modules/Item.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    Items: typeof import('./src/views/modules/Items.vue')['default']
    Login: typeof import('./src/views/modules/Login.vue')['default']
    NotFound: typeof import('./src/views/pages/NotFound.vue')['default']
    Options: typeof import('./src/components/Options.vue')['default']
    Orders: typeof import('./src/views/modules/Orders.vue')['default']
    Profile: typeof import('./src/views/modules/Profile.vue')['default']
    ProfileBanner: typeof import('./src/components/ProfileBanner.vue')['default']
    Restaurant: typeof import('./src/views/pages/Restaurant.vue')['default']
    RestaurantAdmin: typeof import('./src/views/modules/RestaurantAdmin.vue')['default']
    RestaurantBanner: typeof import('./src/components/RestaurantBanner.vue')['default']
    RestaurantCard: typeof import('./src/components/RestaurantCard.vue')['default']
    RestaurantInfo: typeof import('./src/components/RestaurantInfo.vue')['default']
    Restaurants: typeof import('./src/views/pages/Restaurants.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfCheckout: typeof import('./src/components/SelfCheckout.vue')['default']
    ShowCode: typeof import('./src/components/ShowCode.vue')['default']
    User: typeof import('./src/views/pages/User.vue')['default']
    UserAbout: typeof import('./src/views/modules/UserAbout.vue')['default']
  }
}
